### PR TITLE
OPCUA simulator implementation

### PR DESCRIPTION
**Pull request by Sphingobium**
# Description

Implements @amine-amaach s OPCUA simulator into our stack so we can test with OPC UA data. Documentation of the application: https://github.com/amine-amaach/simulators/tree/main/ioTSensorsOPCUA

## Type of change

Please delete options that are not relevant.

- [X] New feature (non-breaking change which adds functionality)
- [X] This change requires a documentation update

# How Has This Been Tested?

Autodeploying

# Checklist:

- [ ] I have made corresponding changes to the documentation
- [ ] I have made corresponding changes to the changelog (if needed).
- [ ] I have made corresponding notices to the upgrade instructions (if needed)

### CODE REVIEW

**Comment by Scarjit** [comment]
@Sphingobium Whats the current status of this draft ?

**Comment by Scarjit** [comment]
Added to Changelog (0.9.10)

**Review by DaruZero — APPROVED** [review]
LGTM

**Review by DaruZero — APPROVED** [review]
🚀

**Review by JeremyTheocharis — APPROVED** [review]

**Pull request merged**
