### PR TITLE
feat: new database definition

### LINKED ISSUE #648: Create new database model using DDL "v1.0.0 preview" and upload to documentation
See also comments in #367

### PR DESCRIPTION
**Pull request by Scarjit**
# Description
This pull requests provides the database definition for our new database model.

Fixes #648 

## Type of change

Please delete options that are not relevant.

- [X] New feature (non-breaking change which adds functionality)
- [X] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [X] This change requires a documentation update

# How Has This Been Tested?

Not tested

# Checklist:

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] Any dependent changes have been merged and published in downstream modules
- [ ] I have checked that my issue complies with the [Contributing guidelines](https://github.com/united-manufacturing-hub/united-manufacturing-hub/blob/main/CONTRIBUTING.md)
- [x] I have made corresponding changes to the documentation

### CODE REVIEW

**Comment by Gornoka** [comment]
maybe we should discuss the **scrap logic** topic in an even  larger round :P

**Comment by JeremyTheocharis** [comment]
Let's try to create a documentation an the same time to explain the datamodel. I find it pretty hard to understand it and I've been in at least 60% of the discussions. 

Could you protocol your meeting? e.g., explain your reasoning behind scrap. I can then use it for the explaination of the datamodel. Will probably create an entire sub-section in our documentation just for that.

**Comment by JeremyTheocharis** [comment]
Also find the latest visualization here: https://dbdiagram.io/d/61a4912d8c901501c0d6e070

**Comment by JeremyTheocharis** [comment]
I will prioritize #714 first to create a solid foundation for our documentation.

**Comment by Scarjit** [comment]
> Also find the latest visualization here: https://dbdiagram.io/d/61a4912d8c901501c0d6e070
You can also use the latest rendering:

**Comment by JeremyTheocharis** [comment]
Could you elaborate further on the following tables / data models?

1. Process, ProcessGroupRelations?
2. StationStep, StationStepSequence, etc.?
3. Product.Status, ProductStatus, ProductFailureId, ProductFailure?

The rest seems to be clear to me

**Comment by larswitte** [comment]
> Could you elaborate further on the following tables / data models?
> 
>     1. Process, ProcessGroupRelations?
> 
>     2. StationStep, StationStepSequence, etc.?
> 
>     3. Product.Status, ProductStatus, ProductFailureId, ProductFailure?
> 
> 
> The rest seems to be clear to me

**2. StationStep** (In regards to the digital shadow. I do not have the full overview.)
`StationStep` could be used by the digital shadow like asset was used in the "old" database. The problem with asset is, that if we want to model different *steps* at one asset in the digital shadow, we have no other option then to make multiple asset in the database at one physical station/machine/asset (one for every step). This does not really fit well with the word asset and it would work better with something like step. Additionally the word asset is generally relatively ambiguous.

**3. Product.Status, ProductStatus**
Currently we are using the `isScrap` boolean in the corresponding uniqueProductTable. @Gornoka has brought to our attention the problem that a part with `isScrap`  set to *true* might still be repaired or used later. In that sense the part would not be scrap but also not be okay. Instead in the current new database definition the `ProductStatus` enum containing `NotScrap`, `Scrap` and `Undefined` is being used. While I also see the problem of the slightly misleading meaning of `isScrap`=true, I do not think we should include `Undefined`. In my opinion, not knowing about the status of a product is one of many reasons why a product should be defined as not ok. I personally would favour the ProductStatus to just be either `OK` or `NOK` which is being used in the industry. Then we could specify the `NOK` state by using `Undefined` or `Missing Data` etc. in the ProductFailure Table.

**3. ProductFailureId, ProductFailure** *- new feature, not currently used, I like the idea -*
Currently if a part is not ok, `isScrap` is set to true without further information being stored. Let's say we have multiple measurements with individual thresholds processed by the edge devices to get the `isScrap` status. The amount of measurements and the thresholds will probably change over time. If we have processes with a lot of reasons, why a product can be scrapped, this might get difficult to analyze very fast. Linking specific failure reasons to problematic parts with the ProductFailureId might make later analysis a lot easier.

**Comment by JeremyTheocharis** [comment]
Thank you for the explanation @larswitte !

I agree with it and understood it. Regarding the `OK`, `NOK` discussion we should go for the following behavior:

A compomise: A product is by default `OK` until it is measured to be `NOK` (as this is the wanted behavior for most industries, as 100 % quality control is very rare). During the creation of the product it is possible to set it to `Undefined` for industries with 100% quality control. If this flag or whatever is not set, it will be `OK` by default until is is `NOK`.

We need to think about renaming the MQTT messages and include the behavior mentioned above

**Review by JeremyTheocharis — APPROVED** [review]

**Comment by larswitte** [comment]
To make the transfer from the old to the new database a little bit easier, I made a table containing translations regarding the digital shadow. Except for naming, the digital shadow structure stays mostly the same.

| New Table/Variable Name | Old Table/Variable Name| Description |
|--------------|-----------|------------|
| **Product** | uniqueProductTable     |   Table      |
| Id      | uniqueProductID  | Stored in new table *Product*       |
| StationStepId | asset_id | Stored in new table *Product*    |
|StationProductID| product_id|Stored in new table *Product* |
| StationStepId | asset_id | Stored in new table *Product*    |
|ProductionBegin|begin_timestamp_ms|Stored in new table *Product*|
|ProductionEnd|end_timestamp_ms|Stored in new table *Product*|
| Status | is_scrap | Stored in new table *Product*  (slightly changed: added undefined state)  |
| ProductFailureId | - | Stored in new table *Product*,  (new)  |
| **ProductInheritance** | productInheritanceTable     |       Table  |
|ParentId|parent_uid|Stored in new table *ProductInheritance*|
|ChildId|child_uid|Stored in new table *ProductInheritance*|
| **ProductTagString** | productTagStringTable     |     Table   |
|Id| -  | Stored in new table *ProductTagString*, (new)|
|Timestamp|timestamp|Stored in new table *ProductTagString*|
|ProductId|product_uid|Stored in new table *ProductTagString*|
|ValueName|valueName|Stored in new table *ProductTagString*|
|Value|value|Stored in new table *ProductTagString*|
| **ProductTagDouble** | productTagTable     |  Table       |
|Id| - |Stored in new table *ProductTagDouble*, (new)|
|Timestamp|timestamp|Stored in new table *ProductTagDouble*|
|ProductId|product_uid|Stored in new table *ProductTagDouble*|
|ValueName|valueName|Stored in new table *ProductTagDouble*|
|Value|value|Stored in new table *ProductTagDouble*|
|**StationStepProduct**| productTable| Table containing product type information *referenced by Product*|
|**ProductFailure**| - | New table containing information about failure reasons *referenced by Product*, (new)|
|**StationStep**| assetTable | Process/Asset specific Table *referenced by Product*|

**Comment by Gornoka** [comment]
Is this dead dead or still in some form of delayed state ?

**Comment by Scarjit** [comment]
> Is this dead dead or still in some form of delayed state ?

Currently on ice, due to our current effort to increase stability

**Pull request closed without merging**
