### PR TITLE
Factoryinsight api v2

### PR DESCRIPTION
**Pull request by Scarjit**
# Description

This pr introduces a new API for our upcoming Frontend changes

## Type of change

- [X] New feature (non-breaking change which adds functionality)
- [ ] This change requires a documentation update

# How Has This Been Tested?

- [X] All queries return data
- [x] All queries return *correct* data

### CODE REVIEW

**Comment by JeremyTheocharis** [comment]
Todo: if there is a timestamp out of the selected range and LOCF is selected, it should also fetch the timestamp before the selected range to prevent null values at the beginning of the selected range

**Comment by JeremyTheocharis** [comment]
Todo: fine-tune service-dataformat.go so it e.g. shows custom tags (even when there is no state), or does not show jobs (if there is nothing job related)

**Comment by JeremyTheocharis** [comment]
Todo: add endpoint to fetch all enterprises, workcells, lines, etc. to have it in one frontend menu

**Comment by Scarjit** [comment]
> Todo: add endpoint to fetch all enterprises, workcells, lines, etc. to have it in one frontend menu

Is now supported in /treeStructure.

<details>
<summary>Example json</summary>

```json
{
	"factoryinsight": {
		"sites": {
			"testLocation": {
				"areas": {
					"Area1": {
						"productionLines": {
							"ProductionLine1": {
								"workCells": {
									"testMachine": {
										"tables": {
											"availabilityHistogram": {
												"id": 3
											},
											"availabilityTotal": {
												"id": 4
											},
											"jobs": {
												"id": 0
											},
											"performance": {
												"id": 5
											},
											"productTypes": {
												"id": 2
											},
											"products": {
												"id": 1
											},
											"quality": {
												"id": 6
											}
										},
										"kpi": [
											"oee",
											"availability",
											"performance",
											"quality"
										],
										"tags": {
											"standard": [
												"jobs",
												"output",
												"shifts",
												"state",
												"throughput"
											],
											"custom": {
												"0": [],
												"1": [],
												"2": [],
												"3": [],
												"4": [],
												"5": [
													"xawd"
												],
												"6": [],
												"7": [
													"ax"
												],
												"8": [],
												"9": [],
												"a": [
													"1"
												],
												"b": [],
												"c": [
													"x",
													"y"
												],
												"d": [],
												"e": [],
												"f": []
											}
										}
									}
								}
							},
							"ProductionLine2": {
								"workCells": {
									"testMachine": {
										"tables": {
											"availabilityHistogram": {
												"id": 3
											},
											"availabilityTotal": {
												"id": 4
											},
											"jobs": {
												"id": 0
											},
											"performance": {
												"id": 5
											},
											"productTypes": {
												"id": 2
											},
											"products": {
												"id": 1
											},
											"quality": {
												"id": 6
											}
										},
										"kpi": [
											"oee",
											"availability",
											"performance",
											"quality"
										],
										"tags": {
											"standard": [
												"jobs",
												"output",
												"shifts",
												"state",
												"throughput"
											],
											"custom": {
												"0": [],
												"1": [],
												"2": [],
												"3": [],
												"4": [],
												"5": [
													"xawd"
												],
												"6": [],
												"7": [
													"ax"
												],
												"8": [],
												"9": [],
												"a": [
													"1"
												],
												"b": [],
												"c": [
													"x",
													"y"
												],
												"d": [],
												"e": [],
												"f": []
											}
										}
									}
								}
							},
							"ProductionLine3": {
								"workCells": {
									"testMachine": {
										"tables": {
											"availabilityHistogram": {
												"id": 3
											},
											"availabilityTotal": {
												"id": 4
											},
											"jobs": {
												"id": 0
											},
											"performance": {
												"id": 5
											},
											"productTypes": {
												"id": 2
											},
											"products": {
												"id": 1
											},
											"quality": {
												"id": 6
											}
										},
										"kpi": [
											"oee",
											"availability",
											"performance",
											"quality"
										],
										"tags": {
											"standard": [
												"jobs",
												"output",
												"shifts",
												"state",
												"throughput"
											],
											"custom": {
												"0": [],
												"1": [],
												"2": [],
												"3": [],
												"4": [],
												"5": [
													"xawd"
												],
												"6": [],
												"7": [
													"ax"
												],
												"8": [],
												"9": [],
												"a": [
													"1"
												],
												"b": [],
												"c": [
													"x",
													"y"
												],
												"d": [],
												"e": [],
												"f": []
											}
										}
									}
								}
							}
						}
					},
					"Area2": {
						"productionLines": {
							"ProductionLine1": {
								"workCells": {
									"testMachine": {
										"tables": {
											"availabilityHistogram": {
												"id": 3
											},
											"availabilityTotal": {
												"id": 4
											},
											"jobs": {
												"id": 0
											},
											"performance": {
												"id": 5
											},
											"productTypes": {
												"id": 2
											},
											"products": {
												"id": 1
											},
											"quality": {
												"id": 6
											}
										},
										"kpi": [
											"oee",
											"availability",
											"performance",
											"quality"
										],
										"tags": {
											"standard": [
												"jobs",
												"output",
												"shifts",
												"state",
												"throughput"
											],
											"custom": {
												"0": [],
												"1": [],
												"2": [],
												"3": [],
												"4": [],
												"5": [
													"xawd"
												],
												"6": [],
												"7": [
													"ax"
												],
												"8": [],
												"9": [],
												"a": [
													"1"
												],
												"b": [],
												"c": [
													"x",
													"y"
												],
												"d": [],
												"e": [],
												"f": []
											}
										}
									}
								}
							},
							"ProductionLine2": {
								"workCells": {
									"testMachine": {
										"tables": {
											"availabilityHistogram": {
												"id": 3
											},
											"availabilityTotal": {
												"id": 4
											},
											"jobs": {
												"id": 0
											},
											"performance": {
												"id": 5
											},
											"productTypes": {
												"id": 2
											},
											"products": {
												"id": 1
											},
											"quality": {
												"id": 6
											}
										},
										"kpi": [
											"oee",
											"availability",
											"performance",
											"quality"
										],
										"tags": {
											"standard": [
												"jobs",
												"output",
												"shifts",
												"state",
												"throughput"
											],
											"custom": {
												"0": [],
												"1": [],
												"2": [],
												"3": [],
												"4": [],
												"5": [
													"xawd"
												],
												"6": [],
												"7": [
													"ax"
												],
												"8": [],
												"9": [],
												"a": [
													"1"
												],
												"b": [],
												"c": [
													"x",
													"y"
												],
												"d": [],
												"e": [],
												"f": []
											}
										}
									}
								}
							},
							"ProductionLine3": {
								"workCells": {
									"testMachine": {
										"tables": {
											"availabilityHistogram": {
												"id": 3
											},
											"availabilityTotal": {
												"id": 4
											},
											"jobs": {
												"id": 0
											},
											"performance": {
												"id": 5
											},
											"productTypes": {
												"id": 2
											},
											"products": {
												"id": 1
											},
											"quality": {
												"id": 6
											}
										},
										"kpi": [
											"oee",
											"availability",
											"performance",
											"quality"
										],
										"tags": {
											"standard": [
												"jobs",
												"output",
												"shifts",
												"state",
												"throughput"
											],
											"custom": {
												"0": [],
												"1": [],
												"2": [],
												"3": [],
												"4": [],
												"5": [
													"xawd"
												],
												"6": [],
												"7": [
													"ax"
												],
												"8": [],
												"9": [],
												"a": [
													"1"
												],
												"b": [],
												"c": [
													"x",
													"y"
												],
												"d": [],
												"e": [],
												"f": []
											}
										}
									}
								}
							}
						}
					},
					"Area3": {
						"productionLines": {
							"ProductionLine1": {
								"workCells": {
									"testMachine": {
										"tables": {
											"availabilityHistogram": {
												"id": 3
											},
											"availabilityTotal": {
												"id": 4
											},
											"jobs": {
												"id": 0
											},
											"performance": {
												"id": 5
											},
											"productTypes": {
												"id": 2
											},
											"products": {
												"id": 1
											},
											"quality": {
												"id": 6
											}
										},
										"kpi": [
											"oee",
											"availability",
											"performance",
											"quality"
										],
										"tags": {
											"standard": [
												"jobs",
												"output",
												"shifts",
												"state",
												"throughput"
											],
											"custom": {
												"0": [],
												"1": [],
												"2": [],
												"3": [],
												"4": [],
												"5": [
													"xawd"
												],
												"6": [],
												"7": [
													"ax"
												],
												"8": [],
												"9": [],
												"a": [
													"1"
												],
												"b": [],
												"c": [
													"x",
													"y"
												],
												"d": [],
												"e": [],
												"f": []
											}
										}
									}
								}
							},
							"ProductionLine2": {
								"workCells": {
									"testMachine": {
										"tables": {
											"availabilityHistogram": {
												"id": 3
											},
											"availabilityTotal": {
												"id": 4
											},
											"jobs": {
												"id": 0
											},
											"performance": {
												"id": 5
											},
											"productTypes": {
												"id": 2
											},
											"products": {
												"id": 1
											},
											"quality": {
												"id": 6
											}
										},
										"kpi": [
											"oee",
											"availability",
											"performance",
											"quality"
										],
										"tags": {
											"standard": [
												"jobs",
												"output",
												"shifts",
												"state",
												"throughput"
											],
											"custom": {
												"0": [],
												"1": [],
												"2": [],
												"3": [],
												"4": [],
												"5": [
													"xawd"
												],
												"6": [],
												"7": [
													"ax"
												],
												"8": [],
												"9": [],
												"a": [
													"1"
												],
												"b": [],
												"c": [
													"x",
													"y"
												],
												"d": [],
												"e": [],
												"f": []
											}
										}
									}
								}
							},
							"ProductionLine3": {
								"workCells": {
									"testMachine": {
										"tables": {
											"availabilityHistogram": {
												"id": 3
											},
											"availabilityTotal": {
												"id": 4
											},
											"jobs": {
												"id": 0
											},
											"performance": {
												"id": 5
											},
											"productTypes": {
												"id": 2
											},
											"products": {
												"id": 1
											},
											"quality": {
												"id": 6
											}
										},
										"kpi": [
											"oee",
											"availability",
											"performance",
											"quality"
										],
										"tags": {
											"standard": [
												"jobs",
												"output",
												"shifts",
												"state",
												"throughput"
											],
											"custom": {
												"0": [],
												"1": [],
												"2": [],
												"3": [],
												"4": [],
												"5": [
													"xawd"
												],
												"6": [],
												"7": [
													"ax"
												],
												"8": [],
												"9": [],
												"a": [
													"1"
												],
												"b": [],
												"c": [
													"x",
													"y"
												],
												"d": [],
												"e": [],
												"f": []
											}
										}
									}
								}
							}
						}
					}
				}
			}
		}
	}
}
```
</details>

**Comment by Scarjit** [comment]
> Todo: if there is a timestamp out of the selected range and LOCF is selected, it should also fetch the timestamp before the selected range to prevent null values at the beginning of the selected range

Done

**Comment by Scarjit** [comment]
> Todo: fine-tune service-dataformat.go so it e.g. shows custom tags (even when there is no state), or does not show jobs (if there is nothing job related)

Added

**Comment by Scarjit** [comment]
Superseded by #1322

**Pull request closed without merging**
