### PR TITLE
feat: Merge factorycube-server & factorycube-edge

### LINKED ISSUE #625: Simplify helm charts & add templates
**Is your feature request related to a problem? Please describe.**
The current split between factorycube-edge and server duplicates some functionality and makes the stack more difficult to maintain.

Subissues:
 - [x] #637 
 - [x] #638

Resolves:
 - #547

### PR DESCRIPTION
**Pull request by Scarjit**
# Description

This pr merges factorycube-server & factorycube-edge.

Fixes #625 

## Type of change

Please delete options that are not relevant.

- [X] New feature (non-breaking change which adds functionality)
- [X] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [X] This change requires a documentation update

# How Has This Been Tested?

Not yet tested

**Test Configuration**:
* Kubernetes Version: 
* Helm Version:
* Hardware:

# Checklist:

- [X] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] New and existing unit tests pass locally with my changes
- [X] I have checked that my issue complies with the [Contributing guidelines](https://github.com/united-manufacturing-hub/united-manufacturing-hub/blob/main/CONTRIBUTING.md)

### CODE REVIEW

**Comment by JeremyTheocharis** [comment]
This PR fixes #637 

One idea;

## Idea
My idea would be to have these options to choose from in the Helm chart:

1. development (default, edge-recommended and server-recommended)
2. edge-recommended (previously `factorycube-edge`, will contain our recommended setup for the edge)
3. server-recommended (previously `factorycube-server`, will contain our recommended setup for the server)
4. customized (being able to adjust every small parameter like we have currently in the Helm chart)

### edge-recommended
```yaml
edge-recommended:
    enabled: true
    node-red-plugins: loremipsum
    sensorconnect-iprange: loremipsum
    mqttBridgeURL: loremipsum
...
```

### server-recommended
```yaml
server-recommended:
    enabled: true
    blob-enabled: true
    timescaledb-enabled: true
...
```

## the end

The goal should be, that a non-IT-person can work with the system without being overwhelmed by the sheer number of parameters (e.g., having the recommended setups at the beginning), while an IT person can still overwrite the recommended settings.

But this is all just an idea. Maybe you can look it up how it is done in similar complicated Helm charts?

btw: let's remove the pycache stuff :)

**Comment by Scarjit** [comment]
This [chart ](https://artifacthub.io/packages/helm/prometheus-community/kube-prometheus-stack?modal=values) has default rules at the very top of the chart.

**Comment by JeremyTheocharis** [comment]
# Ideas

- Installer asking for parameters
- Bash script AFTER installation to help with initial installation
- move all parameters that are changed via bash script into upper area
- rename all important paramters to have the same beginning, e.g., "000_...."

## User Stories

- You have installed factorycube-edge, but now want to enable "dashboard"
- You have server, but now want additionally blob

## Priority

1. Move important configurations into upper area of Helm chart
2. Make then Helm chart work (e.g., remove emqxedge)
3. Write bash script for after installation configuration

**Comment by Scarjit** [comment]
Now passes helm lint & yamllint

**Comment by Scarjit** [comment]
Still has an issue, when using helm install:
```

PS C:\Users\FerdinandLinnenberg\Desktop\united-manufacturing-hub\deployment\factorycube-unified> helm install factorycube-unified . -n factorycube-unified --values .\values.yaml
coalesce.go:199: warning: cannot overwrite table with non table for priorityClassName (map[])
Error: INSTALLATION FAILED: template: factorycube-unified/templates/timescaledb-secrets.yaml:18:16: executing "factorycube-unified/templates/timescaledb-secrets.yaml" at <include "clusterName" .>: error calling include: template: no template "clusterName" associated with template "gotpl"

```

**Review by JeremyTheocharis — APPROVED** [review]

**Pull request merged**
