### PR TITLE
fix: mqtt kafka bridge not re subscribing after mqtt disconnection

### LINKED ISSUE #742: mqtt-kafka-bridge not re-subscribing after MQTT disconnection
Can be reproduced by killing the VerneMQ pod. Although the log says that the connection is restablished, there are no MQTT messages going through. After restarting mqtt-kafka-bridge pod it works again.

### PR DESCRIPTION
**Pull request by Scarjit**
This fixes #742 by restarting the application until the connection can be re-established.

### CODE REVIEW

**Comment by Scarjit** [comment]
I have also added an timeout for the redis cache lookup, to prevent it from blocking the app.

**Review by JeremyTheocharis — APPROVED** [review]

**Comment by Scarjit** [comment]
@JeremyTheocharis Can you re-start the docker builds for this pr ?

**Comment by JeremyTheocharis** [comment]
Apparently, CodeQL now warns of log4j similar attacks and prevents this PR from being merged. Are these warnings reasonable?

**Comment by Scarjit** [comment]
> Apparently, CodeQL now warns of log4j similar attacks and prevents this PR from being merged. Are these warnings reasonable?

While zap is to my knowledge not vulnerable, we should offer an wrapper function to sanitize our log output.

**Pull request merged**
