### PR TITLE
feat: remove landingpage from documentation

### LINKED ISSUE #680: Remove landingpage from documentation
When you currently go to docs.umh.app, you are greeted by a "start page", which currently adds no value, so I suggest removing it.

### PR DESCRIPTION
**Pull request by Scarjit**
Closes #680

### CODE REVIEW

**Comment by kruegeralex** [comment]
Hi @Scarjit for the quick implementation! When I click on the preview link, only this empty page appears (see attachment). If I then click on "Documentation" (top right), the normal documentation appears.
image

**Comment by Scarjit** [comment]
@kruegeralex Thats why the pull request is still a draft ;)

**Comment by Scarjit** [comment]
After trying out multiple methods, that the internet says would redirect the page, i think it would be easier to make the redirect at webserver level.
This would also reduce the problems with old browsers who don't understand the refresh meta tag.

@JeremyTheocharis Can you make an 301 redirect from https://docs.umh.app to https://docs.umh.app/docs in our webserver ?

**Comment by JeremyTheocharis** [comment]
> After trying out multiple methods, that the internet says would redirect the page, i think it would be easier to make the redirect at webserver level. This would also reduce the problems with old browsers who don't understand the refresh meta tag.
> 
> @JeremyTheocharis Can you make an 301 redirect from https://docs.umh.app to https://docs.umh.app/docs in our webserver ?

Done :)

**Pull request closed without merging**
