### PR TITLE
New feature to simulate IoT sensor data over MQTT  

### PR DESCRIPTION
**Pull request by amine-amaach**
# Description

**IoTSensorsMQTT** is an IoT sensor data simulator that allows you to realistically simulate multiple IoT sensors with great flexibility and minimal configuration. The simulator generates data based on the mean and standard deviation of the real sensors and then publishes this data over MQTT.

> For more information, check out the project's [repository](https://github.com/amine-amaach/simulators/tree/main/ioTSensorsMQTT). 

* Example for configuring the simulator :
```json
{
    "MQTT_BROKER": {
        "SERVER_URL":"mqtt://broker.hivemq.com:1883",
        "SERVER_USER": "",
        "SERVER_PWD": "",
        "SERVER_RETAIN": "true",
        "SERVER_QOS": 1,
        "CLIENT_ID": "IoTSensorsMQTT-Simulator",
        "KEEP_ALIVE": 300, 
        "RETRY_DELAY": 10,
        "ROOT_TOPIC": "IoTSensorsMQTT",
        "SET_DELAY_BETWEEN_MESSAGES" : 30,
        "RANDOMIZE_DELAY_BETWEEN_MESSAGES" : "true"
    },   

    "SIMULATORS": [
        {
            "Name" : "Temperature",
            "Mean" : 50.0,
            "StandardDeviation" : 3.0
        },
        {
            "Name" : "Pressure",
            "Mean" : 80.0,
            "StandardDeviation" : 9.0
        },
        {
            "Name" : "Humidity",
            "Mean" : 40.0,
            "StandardDeviation" : 3.0
        }
    ]
}
```
* Description of the above example : 

> SERVER_URL

* The MQTT broker url.

> SERVER_USER

* The name of the MQTT user with subscribe and publish permissions.

> SERVER_PWD

* The password for the MQTT user with subscribe and publish permissions.

> CLIENT_ID

* The client id to use when connecting to the broker.

> SET_DELAY_BETWEEN_MESSAGES

* Allows you to set the delay between data points in seconds.

> RANDOMIZE_DELAY_BETWEEN_MESSAGES

* Allows you to randomize the duration between data points, when set to `false` SET_DELAY_BETWEEN_MESSAGES is used as fixed duration.

> ROOT_TOPIC

* Allows you to set a root topic for the simulated sensors.

> SIMULATORS

* Allows you to define the desired sensors with their parameters.

  > Name : The sensor's name.
  
  > Mean : The data mean of the actual sensor.
  
  > StandardDeviation : The data Standard Deviation of the actual sensor.

## Type of change

- [x] New feature (non-breaking change which adds functionality)

# How Has This Been Tested?

This feature is tested on a development environment using a DigitalOcean Kuberenetes cluster with two nodes of 2 vCPUs and 4GB RAM each. The platform is deployed using the following minimal-installation values :

```yaml
---
# Please adjust the following lines
# _000_commonConfig contains the most common configuration options. To go into the details you can look into the configurations option after _000_commonConfig
_000_commonConfig:
  serialNumber: "default"  # usually the hostname
  # This allows to specify data sources, which is mostly used for instances running on the edge
  datasources:

    # barcodereader reads out connected USB barcodereaders emulating a keyboard
    barcodereader:
      enabled: false
      USBDeviceName: "Datalogic ADC, Inc. Handheld Barcode Scanner"
      USBDevicePath: "" # Linux device path, if empty, USBDeviceName is used
      customerID: "raw"
      location: "barcodereader"
      machineID: "barcodereader"

    # sensorconnect searches for ifm IO-Link gateways and reads out the connected sensors
    sensorconnect:
      enabled: false
      iprange: "192.168.10.1/24"  # IP Range in CIDR notation
      enableKafka: true
      enableMQTT: false

    cameraconnect:
      enabled: false

    # iotsensorsmqtt simulates IoT sensor data and publishes it over MQTT.
    iotsensorsmqtt:
      enabled: true

  # dataprocessing involves microservices, whose main purpose is to process the data
  dataprocessing:
    nodered:
      enabled: true
      defaultFlows: false

  # Infrastructure
  infrastructure:

    # vernemq
    mqtt:
      enabled: true
      AclConfig: |-
        pattern #

    # apache kafka, mqttkafkabridge, kowl, kafkatopostgresql
    kafka:
      enabled: true
      useSSL: false
      defaultTopics: ia.test.test.test.processValue;ia.test.test.test.count

  # timescaledb, factoryinsight, grafana, redis
  # datastorage is the basic infrastructure to get messages from MQTT, storing them in a database and exposing a REST API with KPIs that can be used in Grafana (contains timescaledb, factoryinsight, mqtt-to-postgresql, grafana, vernemq, )
  # If you want to enable only some of these components, set enabled to false and enable them in the detailed configuration below 000_commonConfig
  datastorage:
    enabled: true
    db_password: "changeme"

  # factoryinput, grafanaproxy
  datainput:
    enabled: false

# custom changes for minimal version
factoryinsight:
  replicas: 1
  hpa:
    enabled: false
  pdb:
    enabled: false
  resources:
    limits:
      cpu: 200m
      memory: 200Mi
    requests:
      cpu: 50m
      memory: 50Mi
kafkatopostgresql:
  replicas: 1
  resources:
    limits:
      cpu: 200m
      memory: 200Mi
    requests:
      cpu: 50m
      memory: 50Mi
kafka:
  heapOpts: -Xmx500m -Xms500m
  zookeeper:
    heapSize: 128
  resources:
    limits:
      cpu: 1000m
      memory: 1Gi
    requests:
      cpu: 100m
      memory: 250Mi
redis:
  replica:
    replicaCount: 1
    resources:
      limits:
        cpu: 200m
        memory: 200Mi
      requests:
        cpu: 100m
        memory: 100Mi
  master:
    extraFlags:
      - --maxmemory 200mb
    resources:
      limits:
        cpu: 200m
        memory: 200Mi
      requests:
        cpu: 100m
        memory: 100Mi
vernemq:
  replicas: 1
  additionalEnv:
    - name: DOCKER_VERNEMQ_ALLOW_REGISTER_DURING_NETSPLIT
      value: "on"
    - name: DOCKER_VERNEMQ_ALLOW_PUBLISH_DURING_NETSPLIT
      value: "on"
    - name: DOCKER_VERNEMQ_ALLOW_SUBSCRIBE_DURING_NETSPLIT
      value: "on"
    - name: DOCKER_VERNEMQ_ALLOW_UNSUBSCRIBE_DURING_NETSPLIT
      value: "on"
    - name: DOCKER_VERNEMQ_ALLOW_ANONYMOUS
      value: "on"
    - name: DOCKER_VERNEMQ_MAX_ONLINE_MESSAGES
      value: "1000"
    - name: DOCKER_VERNEMQ_MAX_OFFLINE_MESSAGES
      value: "1000"
    - name: DOCKER_VERNEMQ_LISTENER__SSL__CAFILE
      value: /etc/ssl/vernemq/ca.crt
    - name: DOCKER_VERNEMQ_LISTENER__SSL__CERTFILE
      value: /etc/ssl/vernemq/tls.crt
    - name: DOCKER_VERNEMQ_LISTENER__SSL__KEYFILE
      value: /etc/ssl/vernemq/tls.key
    - name: DOCKER_VERNEMQ_ACCEPT_EULA
      value: "yes"
    - name: DOCKER_VERNEMQ_LISTENER__SSL__DEFAULT__USE_IDENTITY_AS_USERNAME
      value: "on"
    - name: DOCKER_VERNEMQ_LISTENER__SSL__DEFAULT__REQUIRE_CERTIFICATE
      value: "on"
    - name: DOCKER_VERNEMQ_LEVELDB.maximum_memory
      value: "50mb"
    - name: DOCKER_VERNEMQ_LISTENER__TCP__ALLOWED_PROTOCOL_VERSIONS
      value: 3,4,5
  resources:
    limits:
      cpu: 500m
      memory: 500Mi
    requests:
      cpu: 100m
      memory: 100Mi

```

**Test Configuration**:
* Kubernetes Version: v1.23.9
* Helm Version: v1.23.9
* Hardware: DigitalOcean Kuberenetes cluster

## A Node-Red flow to use the simulator :
```json
[{"id":"06717f7a13826121","type":"tab","label":"IoTSensorsMQTT Simulator","disabled":false,"info":""},{"id":"7d028da489468d06","type":"group","z":"06717f7a13826121","name":"IoTSensorsMQTT Simulator","style":{"stroke":"#ffC000","fill":"#ffefbf","fill-opacity":"0.6","label":true,"label-position":"n","color":"#3f3f3f"},"nodes":["7674c2d1fabfa56f","ddab60ce98e0f655","f674a6066aa7c5b7","6a20ec2e104be4d1","102542971f6e2dab","a5da01fcad5f2a85"],"x":174,"y":39,"w":912,"h":162},{"id":"7674c2d1fabfa56f","type":"mqtt in","z":"06717f7a13826121","g":"7d028da489468d06","name":"IoTSensors raw data","topic":"ia/raw/development/ioTSensors/#","qos":"1","datatype":"auto","broker":"a09f8b607382b939","nl":false,"rap":true,"rh":0,"x":290,"y":120,"wires":[["ddab60ce98e0f655"]]},{"id":"ddab60ce98e0f655","type":"switch","z":"06717f7a13826121","g":"7d028da489468d06","name":"","property":"topic","propertyType":"msg","rules":[{"t":"cont","v":"Humidity","vt":"str"},{"t":"cont","v":"Temperature","vt":"str"},{"t":"cont","v":"Pressure","vt":"str"}],"checkall":"true","repair":false,"outputs":3,"x":490,"y":120,"wires":[["f674a6066aa7c5b7"],["6a20ec2e104be4d1"],["102542971f6e2dab"]]},{"id":"f674a6066aa7c5b7","type":"function","z":"06717f7a13826121","g":"7d028da489468d06","name":"Humidity","func":"msg.payload = {\n    \"timestamp_ms\": Date.now(),\n    \"Humidity\": parseFloat(msg.payload)\n}\nmsg.topic = \"ia/factoryinsight/testLocation/testMachine/processValue/Humidity\"\nreturn msg;","outputs":1,"noerr":0,"initialize":"","finalize":"","libs":[],"x":660,"y":80,"wires":[["a5da01fcad5f2a85"]]},{"id":"6a20ec2e104be4d1","type":"function","z":"06717f7a13826121","g":"7d028da489468d06","name":"Temperature","func":"msg.payload = {\n    \"timestamp_ms\": Date.now(),\n    \"Temperature\": parseFloat(msg.payload)\n}\nmsg.topic = \"ia/factoryinsight/testLocation/testMachine/processValue/Temperature\"\nreturn msg;","outputs":1,"noerr":0,"initialize":"","finalize":"","libs":[],"x":670,"y":120,"wires":[["a5da01fcad5f2a85"]]},{"id":"102542971f6e2dab","type":"function","z":"06717f7a13826121","g":"7d028da489468d06","name":"Pressure","func":"msg.payload = {\n    \"timestamp_ms\": Date.now(),\n    \"Pressure\": parseFloat(msg.payload)\n}\nmsg.topic = \"ia/factoryinsight/testLocation/testMachine/processValue/Pressure\"\nreturn msg;","outputs":1,"noerr":0,"initialize":"","finalize":"","libs":[],"x":660,"y":160,"wires":[["a5da01fcad5f2a85"]]},{"id":"a5da01fcad5f2a85","type":"mqtt out","z":"06717f7a13826121","g":"7d028da489468d06","name":"IoTSensors contextualized data","topic":"","qos":"1","retain":"","respTopic":"","contentType":"","userProps":"","correl":"","expiry":"","broker":"a09f8b607382b939","x":930,"y":120,"wires":[]},{"id":"a09f8b607382b939","type":"mqtt-broker","name":"","broker":"united-manufacturing-hub-vernemq-local-service","port":"1883","clientid":"","usetls":false,"protocolVersion":"4","keepalive":"60","cleansession":true,"birthTopic":"","birthQos":"0","birthPayload":"","birthMsg":{},"closeTopic":"","closeQos":"0","closePayload":"","closeMsg":{},"willTopic":"","willQos":"0","willPayload":"","willMsg":{},"sessionExpiry":""}]
```

### CODE REVIEW

**Comment by amine-amaach** [comment]
I have also tested it using a local **_k3d_** cluster.

**Comment by Scarjit** [comment]
@amine-amaach Ill test it using our internal k3os cluster today, and if successfully ill merge it :)

**Review by Scarjit — APPROVED** [review]

**Comment by Scarjit** [comment]
@JeremyTheocharis This needs your approvement, as a code owner.

**Review by JeremyTheocharis — APPROVED** [review]
Approving to not stop the development process

**Pull request merged**
