### PR TITLE
Rework data model for image and image recognition

### LINKED ISSUE #261: Rework data model for image and image recognition

### PR DESCRIPTION
**Pull request by JeremyTheocharis**
Fixes #261 

The idea behind is that images are send originally into the topic `ia/rawImage/<transmitterID>/<cameraID>`

In the next step they are classified and one of two messages are created:

1. /uniqueProduct and therefore creating a new uniqueProduct, that can be traced through the entire factory.
2. classifyUniqueProduct, in case the unique product exists already

There are no database changes needed, maybe a change in mqtt-to-postgresql to include the new messages.

mqtt-to-blob stores all images into the blob storage using the uniqueProductID
factoryinsight is expanded with multiple functions to retrieve the uniqueIDs, e.g. getBadProductUIDs
The Grafana plugin is then retrieving the uniqueProductIDs and then fetching the corresponding pictures from the blob storage

### CODE REVIEW

**Comment by JeremyTheocharis** [comment]
# Updated proposal

dataflow_imagedata

## Messages

### Topic: ia/rawImage/

All raw data coming in via [cameraconnect]. The full dataflow for images is shown here:

{{< imgproc dataflow_imagedata.png Fit "1200x1200" >}}Full dataflow for capturing, classifying and processing image data{{< /imgproc >}}

Topic structure: `ia/rawImage/<transmitterID>/<cameraID>`

`image_bytes`: base64 encoded image
`image_height`: height of the image in pixel
`image_width`: width of the image in pixel
`image_channels`: amount of included color channels

#### Example for ia/rawImage/

Topic: `ia/rawImage/2020-0102/4646548`

This means that the transmitter with the serial number `2020-0102` has one camera connected to it with the serial number `4646548`.

```json
{
        "timestamp_ms": 1588879689394, 
        "image": {
            "image_bytes": 9j/4AAQSkZJRgABAQAAAQABAAD/2wBD ... 
            "image_height": 800,
            "image_width": 1203,
            "image_channels": 3,
        }
}
```
### /productImage

Topic: `ia/<customerID>/<location>/<AssetID>/productImage`

A message is sent here each time a picture of a unique product is taken.

`UID` in the JSON is a string and the UID of a uniqueProduct.
`imageUID` in the JSON is a string and the UID of a image
`image` in the JSON is a dictionary according to `/rawImage`

#### Example for /productImage

```json
{
    "timestamp_ms": 1588879689394, 
    "UID": "48937222657",
    "imageUID": "2021-03-16T15:33:02Z_camera1" 
    "image": {
        "image_bytes": 9j/4AAQSkZJRgABAQAAAQABAAD/2wBD ... 
        "image_height": 800,
        "image_width": 1203,
        "image_channels": 3,
    }
}
```

### /addOrChangeUniqueProductData

A message is sent here each time a unique product has additional data associated with it, e.g., a image classification or test result. 

#### Example for /addOrChangeUniqueProductData

```json
{
  "UID": "161117101271788647991611171016443",
  "isScrap": false,
  "name": "classification",
  "value": "alignment3_error"
}
```

**Comment by JonaVo** [comment]
Hi, great push. 
In addition, we would like to include a trigger module, which sends a trigger signal via mqtt. Idealy, the camera connect module would listen to this "trigger" topic an react accordingly. 
From a technical perspective, the trigger could be a light barrier or sth similar.

I suggest the following adjustments. Please feel free to elaborate on these. Thanks a lot.

123127315-72957d00-d44a-11eb-958f-a572ad7a64e0

**Topic: ia/trigger/**
All message published on this topic will be interpreted as a trigger

Topic structure: ia/trigger/"transmitterID"/"cameraID"

**Example for ia/trigger/**
Topic: ia/trigger/2020-0102/4646548

This means that the trigger module will trigger the camera with serial number 4646548 which is connected to the transmitter with the ID 2020-0102.

**Comment by larswitte** [comment]
**Format for rawImage**
ia/rawImage/<transmitterID>/<SerialNumberCamera>
```.js
{
	"timestamp_ms":` 214423040823
	"image":  {
		"image_id": "<SerialNumberCamera>_<timestamp_ms>"
		"image_bytes": 3495ask484...
		"image_heigth": 800,
		"image_width": 1203,
		"image_channels": 3
	}
}
```

**Format for productImage**
ia/<customer>/<location>/<assetID>/prodcutImage

```.js
{
	"timestamp_ms":` 214423040823
	"image":  {
		"image_id": "<SerialNumberCamera>_<timestamp_ms>"
		"image_bytes": 3495ask484...
		"image_heigth": 800,
		"image_width": 1203,
		"image_channels": 3
	}
}
```

**Format for rawImageClassification**
ia/rawImageClassification/<transmitterID>/<SerialNumberCamera>
```.js
{
	"timestamp_ms": 214423040823
	"image":  {
		"image_id": "<SerialNumberCamera>_<timestamp_ms>"
		"image_bytes": 3495ask484...
		"image_heigth": 800,
		"image_width": 1203,
		"image_channels": 3
	}
	"classification_result":{
		"class": "scratch"
		"probability": 99.994
		"is_scrap":  true
	}
}
```

**Comment by JeremyTheocharis** [comment]
@larswitte Is this PR still needed or did we include everything in the PRs and in your tutorial?

**Comment by JeremyTheocharis** [comment]
Implemented now in product shadow

**Pull request closed without merging**
